version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres-udan
    restart: always
    hostname: postgresdb
    env_file: .env
    volumes:
     - ./pgdata:/var/lib/postgresql/data
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - uda-network
networks:
  uda-network:
      name: uda-network

