version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    hostname: keycloak
    env_file: .env
    ports:
      - 8081:8080
      - 9990:9990
      - 8443:8443
    command:
      - start-dev
    networks:
      - uda-network
networks:
  uda-network:
    name: uda-network
