version: '3.9'
services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx-server-udan
    volumes:
      - ./localhost.conf:/etc/nginx/conf.d/localhost.conf
      - ./data/build/:/usr/share/nginx/html/dist/
      - ./certs/:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - uda-network

networks:
  uda-network:
    name: uda-network
