CREATE DATABASE IF NOT EXISTS keycloak;
CREATE DATABASE IF NOT EXISTS udan;

-- CREATE USER 'udan'@'%' IDENTIFIED BY 'Pa55w0rd';

GRANT ALL PRIVILEGES ON `keycloak`.* TO 'udan'@'%';

GRANT ALL PRIVILEGES ON `udan`.* TO 'udan'@'%';

FLUSH PRIVILEGES;
